reportes/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
	url(r'^pdf/(?P<id_reporte>[\d]+)$', views.ReportView.as_view(), name='pdf-view')
]

reservas/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'reservar/(?P<id_funcion>[0-9]+)$', views.ReserveView.as_view(), name='reservas-reserve'),
	url(r'comprar/(?P<id_funcion>[0-9]+)$', views.BuyingView.as_view(), name='reservas-buy'),
	url(r'vender/(?P<id_funcion>[0-9]+)/(?P<buying_user>[0-9]+)?$', views.SellingView.as_view(), name='reservas-sell'),
    url(r'pagar-codigo/(?P<codigo>[a-zA-Z0-9]+)$', views.PaymentView.as_view(), name='reservas-payment'),
	url(r'imprimir/(?P<codigo>[a-zA-Z0-9]+)$', views.PrintReserveView.as_view(), name='reservas-print'),
	url(r'codigo/(?P<codigo>[a-zA-Z0-9]+)$', views.CodeView.as_view(), name='reservas-code'),
	url(r'verificar/$', views.VerifyCodeView.as_view(), name='reservas-verifycode')
]

sistema_de_reserva/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from . import views
from simulador.admin import bank_site

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^banco/', include(bank_site.urls)),
    url(r'accounts/', include('usuarios.urls')),
    url(r'peliculas/', include('peliculas.urls')),
    url(r'^$', views.CarteleraView.as_view(), name='inicio'),
    url(r'funciones/', include('funciones.urls')),
    url(r'reservas/', include('reservas.urls')),
	url(r'^reportes/', include('reportes.urls'))
]

urlpatterns += i18n_patterns(
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'accounts/', include('usuarios.urls')),
    prefix_default_language=False
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

reservas/models.py
from django.db import models
from django.db.models import Max

from salas.models import Butaca
from peliculas.models import Pelicula
from funciones.models import Funcion,Precio
from usuarios.models import User

class Banco(models.Model):
	nombre = models.CharField(unique=True, max_length=30)

	def __str__(self):
		return self.nombre


class TipoTarjeta(models.Model):
	nombre = models.CharField(unique=True, max_length=30)
	descripcion = models.CharField(max_length=300, null=False)
	class Meta:
		verbose_name_plural = 'Tipos de tarjeta'
	def __str__(self):
		return self.nombre


class Tarjeta(models.Model):
	nombre = models.CharField(unique=True, max_length=40)
	tipo_tarjeta = models.ForeignKey(TipoTarjeta, on_delete=models.CASCADE, null= False)
	banco = models.ForeignKey(Banco, on_delete=models.CASCADE, null= True)
	habilitada = models.BooleanField(default=True)

	def __str__(self):
		return self.nombre

class Pago(models.Model):
	monto = models.DecimalField(max_digits=16, decimal_places=2)
	# TODO: PROMOCION
	# Si no tiene tarjeta asociada, el pago fue realizado en efectivo
	tarjeta = models.ForeignKey(Tarjeta, on_delete=models.CASCADE, blank=True, null=True)

	def __str__(self):
		if self.tarjeta:
			return '$%.2f con tarjeta %s' % (self.monto, self.tarjeta)
		return '$%.2f en efectivo' % self.monto

class Entrada(models.Model):
	butaca = models.ForeignKey(Butaca, blank=False, null=False)
	funcion = models.ForeignKey(Funcion, blank=False, null=False)

	def estadoentrada_current(self):
		return self.estadoentrada_set.latest('fecha')

	class Meta:
		ordering = ['butaca__fila', 'butaca__columna']
		unique_together = (('butaca','funcion'),)

	def __str__(self):
		return '%s %s' % (str(self.funcion), str(self.butaca))

	def reservar(self, usuario, codigo):
		ee = EstadoEntrada.objects.create(entrada=self, codigo=codigo, usuario=usuario, estado=EstadoEntrada.R)
		ee.save()
	def cancelar(self):
		ee = EstadoEntrada.objects.create(entrada=self, estado=EstadoEntrada.D)
		ee.save()
	def liberar(self):
		ee = EstadoEntrada.objects.create(entrada=self, estado=EstadoEntrada.L)
		ee.save()
	def vender(self, usuario, codigo, precio, pago):
		ee = EstadoEntrada.objects.create(
			entrada=self,
			estado=EstadoEntrada.P,
			codigo=codigo,
			usuario=usuario,
			precio=precio,
			pago=pago
		)
	def reservable(self, *args):
		return self.estadoentrada_current().reservable(*args)
	def cancelable(self, *args):
		return self.estadoentrada_current().cancelable(*args)
	def liberable(self, *args):
		return self.estadoentrada_current().liberable(*args)
	def vendible(self, *args):
		return self.estadoentrada_current().vendible(*args)

class EstadoEntrada(models.Model):
	# Estados Posibles de una Entrada <<enumeration>>
	D, D_TEXT = ("D", "Disponible")
	R, R_TEXT = ("R", "Reservada")
	P, P_TEXT = ("P", "Paga")
	L, L_TEXT = ("L", "Libre")

	ESTADO_CHOICES = (
		(D, D_TEXT),
		(R, R_TEXT),
		(P, P_TEXT),
		(L, L_TEXT),
	)

	def reservable(self):
		return self.entrada.butaca.disponibilidad==Butaca.N and self.estado==EstadoEntrada.D
	def cancelable(self, user):
		return self.estado==EstadoEntrada.R and self.usuario==user
	def liberable(self):
		return self.estado==EstadoEntrada.D or self.estado==EstadoEntrada.R
	def vendible(self, user):
		return self.estado==EstadoEntrada.D or self.estado==EstadoEntrada.L or (self.estado==EstadoEntrada.R and self.usuario==user)

	# id
	estado = models.CharField("Estado", max_length=26, choices=ESTADO_CHOICES, blank=False, null=False)
	entrada = models.ForeignKey(Entrada,on_delete=models.CASCADE, null=False)
	# sha256 -> 64 bytes de digesto hexadecimal
	codigo = models.CharField(null=True, max_length=64)
	fecha = models.DateTimeField("Fecha de cambio de estado", auto_now=True)
	# Si la entrada fue vendida, si o si tendra que tener asociado un pago
	pago = models.ForeignKey(Pago, blank=True, null=True)
	usuario = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
	precio = models.ForeignKey(Precio, on_delete=models.CASCADE, null=True, blank=True)

	def is_newest(self):
		return self == EstadoEntrada.objects.filter(entrada=self.entrada).latest('fecha')

	class Meta:
		ordering = ['-fecha']
		unique_together = (('entrada', 'fecha'),)

	def __str__(self):
		return str(self.entrada)

def _funcion_crear_entradas(instance, created, raw, **kwargs):
	if not created or raw:
		return
	for b in instance.sala.butaca_set.all():
		e,created = Entrada.objects.get_or_create(butaca=b,funcion=instance)
		ee,created = EstadoEntrada.objects.get_or_create(entrada=e, estado=EstadoEntrada.D)
	instance.save()

models.signals.post_save.connect(_funcion_crear_entradas, sender=Funcion, dispatch_uid='_funcion_crear_entradas')

reservas/views.py
import hashlib
import barcode
import math
import io

from django.template.response import TemplateResponse
from django.views import View
from django.shortcuts import render,redirect,get_list_or_404,get_object_or_404
from django.urls import reverse, resolve
from django.utils import timezone
from django.core.serializers import serialize

from .models import Funcion,Precio
from .forms import TarjetaForm, TarjetaOrCashForm, CodeForm
from reservas.models import Entrada, EstadoEntrada, Pago
from usuarios.views import ReservationsView
from usuarios.models import User
from peliculas.views import VerPeliculaView
from sistema_de_reserva import settings

def get_price_context_for_function(funcion):
	return {
		'prices': serialize('json', funcion.precios_vigentes()),
		'pricetypes': serialize('json', {p.tipo_precio for p in funcion.precios_vigentes()})
	}
def get_context_for_map(funcion):
	ctx = {
		'room': serialize('json', [funcion.sala]),
		'seats': serialize('json', funcion.sala.butaca_set.all()),
		'entries': serialize('json', funcion.entrada_set.all()),
		'entrystates': serialize('json', (e.estadoentrada_current() for e in funcion.entrada_set.all())),
	}
	ctx.update(get_price_context_for_function(funcion))
	return ctx
def get_code_svg(code):
	Code39 = barcode.get_barcode_class('code39')
	code39 = Code39(code, add_checksum=False)
	return code39.render({})

def get_codigo(funcion, user):
	digest = hashlib.md5((str(timezone.now()) + str(user.id)).encode('utf8')).digest()
	charset = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ'
	charset_bits = math.floor(math.log(len(charset),2))
	str_digest_bits = math.ceil(len(digest)*8/charset_bits)*charset_bits
	digest = ''.join(bin(x)[2:].zfill(8) for x in digest).zfill(str_digest_bits)
	digits = [int(digest[char0*5:char0*5+5],2) for char0 in range(0, str_digest_bits//5)]
	return ''.join(charset[d] for d in digits)

class ReserveView(View):
	"""
	Vista desde la cual el usuario final reserva entradas
	"""
	def breadcrumbs(id_funcion):
		f = Funcion.objects.get(pk=id_funcion)
		lt = timezone.localtime(f.fecha)
		return VerPeliculaView.breadcrumbs(f.pelicula.id) + [{
			'name': 'El %s a las %s en %s' % (f.fecha.date(), f.fecha.time(), f.sala),
			'url': reverse('reservas-reserve', args=[id_funcion])
		}]
	def post(self, request, id_funcion, *args, **kwargs):
		funcion = get_object_or_404(Funcion, pk=id_funcion)
		codigo = get_codigo(funcion, request.user)
		estadoentradas = [EstadoEntrada.objects.get(pk=eeid) for eeid in request.POST.getlist('entradas')]
		entradas = [ee.entrada for ee in estadoentradas]
		if all(e.reservable() for e in entradas):
			for entrada in entradas:
				entrada.reservar(usuario=request.user, codigo=codigo)
			return ReservationsView().get(request)
		else:
			return self.get(request, id_funcion)

	def get(self, request, id_funcion, *args, **kwargs):
		funcion = get_object_or_404(Funcion, pk=id_funcion)
		pendientes = 0
		if (request.user.is_authenticated()):
			pendientes = EstadoEntrada.objects.filter(usuario=request.user, estado=EstadoEntrada.R)
			pendientes = sum(1 for p in pendientes if p.is_newest())
		if not request.user.is_authenticated():
			max_reserva = 0
		elif request.user.limite_reserva is not None:
			max_reserva = request.user.limite_reserva.max_reserva
		else:
			max_reserva = -1
		ctx = {
			'funcion': funcion,
			'max_reserva': max_reserva,
			'reservas_pendientes': pendientes,
			'breadcrumbs': ReserveView.breadcrumbs(id_funcion),
			'date_input_format': settings.DATE_INPUT_FORMAT_JQUERY,
		}
		ctx.update(get_context_for_map(funcion))
		return TemplateResponse(request, 'reservas/reservar-funcion.html', ctx)

class BuyingView(View):
	"""
	Vista desde la cual el usuario final compra entradas
	"""
	def breadcrumbs(id_funcion):
		f = Funcion.objects.get(pk=id_funcion)
		lt = timezone.localtime(f.fecha)
		return VerPeliculaView.breadcrumbs(f.pelicula.id) + [{
			'name': 'El %s a las %s en %s' % (f.fecha.date(), f.fecha.time(), f.sala),
			'url': reverse('reservas-buy', args=[id_funcion])
		}]
	def post(self, request, id_funcion, *args, **kwargs):
		funcion = get_object_or_404(Funcion, pk=id_funcion)
		estadoentradas = [EstadoEntrada.objects.get(pk=eeid) for eeid in request.POST.getlist('entradas')]
		entradas = [ee.entrada for ee in estadoentradas]
		precios = request.POST.getlist('precio')
		precios = [Precio.objects.get(pk=p_id) for p_id in precios]
		tarjeta = TarjetaForm(request.POST)
		if tarjeta.is_valid() and all(e.vendible(request.user) for e in entradas):
			monto = sum(p.monto for p in precios)
			codigo = get_codigo(funcion, request.user)
			pago = Pago.objects.create(tarjeta=tarjeta.cleaned_data['tarjeta'], monto=monto)
			pago.save()
			for e,p in zip(entradas, precios):
				e.vender(request.user, codigo, p, pago)
			return redirect('accounts-reservations')
		else:
			return self.get(request, id_funcion, tarjeta_form=tarjeta)
	def get(self, request, id_funcion, *args, **kwargs):
		funcion = get_object_or_404(Funcion, pk=id_funcion)
		ctx = {
			'funcion': funcion,
			'breadcrumbs': BuyingView.breadcrumbs(id_funcion),
			'tarjeta_form': kwargs.get('tarjeta_form', TarjetaForm()),
			'date_input_format': settings.DATE_INPUT_FORMAT_JQUERY,
		}
		ctx.update(get_context_for_map(funcion))
		return render(request, 'reservas/comprar-funcion.html', ctx)

class SellingView(View):
	"""
	Vista desde la cual el operador vende entradas
	"""
	def breadcrumbs(id_funcion):
		f = Funcion.objects.get(pk=id_funcion)
		lt = timezone.localtime(f.fecha)
		return VerPeliculaView.breadcrumbs(f.pelicula.id) + [{
			'name': 'El %s a las %s en %s' % (f.fecha.date(), f.fecha.time(), f.sala),
			'url': reverse('reservas-buy', args=[id_funcion])
		}]
	def post(self, request, id_funcion, buying_user=None, *args, **kwargs):
		if not request.user.is_staff:
			return redirect('reservas-buy', id_funcion)
		funcion = get_object_or_404(Funcion, pk=id_funcion)
		estadoentradas = [EstadoEntrada.objects.get(pk=eeid) for eeid in request.POST.getlist('entradas')]
		entradas = [ee.entrada for ee in estadoentradas]
		precios = request.POST.getlist('precio')
		precios = [Precio.objects.get(pk=p_id) for p_id in precios]
		tarjeta = TarjetaOrCashForm(request.POST)
		if buying_user is not None:
			buying_user = User.objects.get(pk=buying_user)
		if tarjeta.is_valid():
			if all(e.vendible(buying_user) for e in entradas):
				monto = sum(p.monto for p in precios)
				codigo = get_codigo(funcion, request.user)
				t = tarjeta.cleaned_data['tarjeta']
				pago = Pago.objects.create(tarjeta=t, monto=monto)
				pago.save()
				for e,p in zip(entradas, precios):
					e.vender(buying_user, codigo, p, pago)
				return self.get(request, id_funcion, buying_user.id if buying_user is not None else None, last_code=codigo)
			else:
				return self.get(request, id_funcion, buying_user.id if buying_user is not None else None, tarjeta_form=tarjeta)
		else:
			return self.get(request, id_funcion, buying_user, tarjeta_form=tarjeta)
	def get(self, request, id_funcion, buying_user=None, *args, **kwargs):
		if not request.user.is_staff:
			return redirect('reservas-buy', id_funcion)
		funcion = get_object_or_404(Funcion, pk=id_funcion)
		context = {
			'funcion': funcion,
			'breadcrumbs': BuyingView.breadcrumbs(id_funcion),
			'tarjeta_form': kwargs.get('tarjeta_form', TarjetaOrCashForm()),
			'date_input_format': settings.DATE_INPUT_FORMAT_JQUERY,
			'last_code': kwargs.get('last_code', None),
			'buying_user': User.objects.get(pk=buying_user) if buying_user is not None else None,
		}
		context.update(get_context_for_map(funcion))
		return render(request, 'reservas/vender-funcion.html', context)

class CodeView(View):
	template_file = 'reservas/ver-codigo.html'

	def post(self, request, codigo):
		precios = request.POST.getlist('precio')
		precios = [Precio.objects.get(pk=precio_id) for precio_id in precios]
		return self.get(request, codigo, precios)

	def get(self, request, codigo, precios=None):
		estadoentradas = get_list_or_404(EstadoEntrada, codigo=codigo)
		estadoentradas = [e for e in estadoentradas if e.is_newest()]
		entradas = [ee.entrada for ee in estadoentradas]
		butacas = [e.butaca for e in entradas]
		funcion = estadoentradas[0].entrada.funcion
		user = estadoentradas[0].usuario
		if request.user != user and not request.user.is_staff:
			return redirect(reverse('accounts-reservations'))
		precios = precios or list(ee.precio for ee in estadoentradas)
		ctx = {
			'funcion': funcion,
			'user': user,
			'code_plain': codigo,
			'code39': get_code_svg(codigo),
			'estadoentradas': list(zip(estadoentradas, precios)),
			'subtotal': sum(p.monto for p in precios if p is not None),
			'allow_sell': all(e.estado==EstadoEntrada.R for e in estadoentradas),
			'date_input_format': settings.DATE_INPUT_FORMAT_JQUERY,
			'entrystates': serialize('json', estadoentradas),
			'entries': serialize('json', entradas),
			'seats': serialize('json', butacas),
			'rooms': serialize('json', [funcion.sala]),
		}
		ctx.update(get_price_context_for_function(funcion))
		return TemplateResponse(request, self.template_file, ctx)

class VerifyCodeView(CodeView):
	template_file = 'reservas/verificar-codigo.html'
	def post(self, request, *args, **kwargs):
		if not request.user.is_staff:
			return redirect('/')
		code_form = CodeForm(request.GET)
		tarjeta_form = TarjetaOrCashForm(request.POST)
		if not tarjeta_form.is_valid() or not code_form.is_valid():
			return self.get(request, code_form, tarjeta_form, *args, **kwargs)

		codigo = code_form.cleaned_data['codigo']
		estadoentradas = EstadoEntrada.objects.filter(codigo=codigo)
		estadoentradas = [e for e in estadoentradas if e.is_newest()]
		precios = request.POST.getlist('precio')
		precios = [Precio.objects.get(pk=p_id) for p_id in precios]
		buying_user = estadoentradas[0].usuario

		if all(ee.vendible(buying_user) for ee in estadoentradas):
			monto = sum(p.monto for p in precios)
			pago = Pago.objects.create(tarjeta=tarjeta_form.cleaned_data['tarjeta'], monto=monto)

templates/reservas/code-metadata.html
<h2>Funcion</h2>
<p>{{ funcion }}</p>
<h2>Usuario</h2>
<table>
	<tbody>
		{% if user %}
			{% if user.persona %}
			<tr><td>Nombre</td><td>{{ user.persona.nombre }}</td></tr>
			<tr><td>Apellido</td><td>{{ user.persona.apellido }}</td></tr>
			<tr><td>Tipo de Documento</td><td>{{ user.persona.tipo_dni }}</td></tr>
			<tr><td>Número de documento</td><td>{{ user.persona.nro_dni }}</td></tr>
			{% else %}
			<tr><td>No se registraron datos personales</td></tr>
			{% endif %}
		<tr><td>Usuario</td><td>{{ user.username }}</td></tr>
		<tr><td>e-Mail</td><td>{% if user.email %}{{ user.email }}{% else %}-{% endif %}</td></tr>
		{% else %}
		No se registron datos personales ni de usuario
		{% endif %}
	</tbody>
</table>
<div class="submit-row">
<a href="{% url 'reservas-sell' id_funcion=funcion.id buying_user=user.id %}"><input type="button" value="Vender más entradas a este usuario"/></a>
</div>

templates/reservas/comprar-funcion.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block head %}
{{ block.super }}
<script type="text/javascript" src="{% static "sitema-de-reserva/vendor/react/react.js" %}"></script>
<script type="text/javascript" src="{% static "sitema-de-reserva/vendor/react/react-dom.js" %}"></script>
<script type="text/javascript" src="{% static "sitema-de-reserva/js/app.js" %}"></script>
<script type="text/javascript">
$(document).ready(function() {
	let rooms = {{ room |safe }};
	let seats = {{ seats|safe }};
	let entryStates = {{ entrystates|safe }};
	let entries = {{ entries|safe }};
	let prices = {{ prices|safe }};
	let pricetypes = {{ pricetypes|safe }};
	StartBuyingMap(document.querySelector('#buy-map'), {
		'rooms': rooms, 'seats': seats, 'entries': entries,
		'entryStates': entryStates, 'prices': prices, 'priceTypes': pricetypes
	});
})
</script>
<link rel="stylesheet" href="{% static 'map.css' %}" />
{% endblock %}

{% block content %}
<!-- Header -->
<div class="topbar-placeholder"></div>
{% include 'peliculas/pelicula-fragment.html' with pelicula=funcion.pelicula %}
<hr/>
{% include 'salas/sala-fragment.html' with sala=funcion.sala %}
<hr/>
<article id="mapa-butacas">
	<h2>Comprando Disponibilidades</h2>
	<a href="{% url 'reservas-reserve' id_funcion=funcion.id%}"><button class="btn btn-default">Reservar</button></a>
	<button class="btn btn-primary">Comprar</button>
	{% if request.user.is_staff %}
	<a href="{% url 'reservas-sell' id_funcion=funcion.id%}"><button class="btn btn-default">Vender</button></a>
	{% endif %}
	<br/>
	<form action="{% url 'reservas-buy' id_funcion=funcion.id %}" method="POST">
		<div class="pantalla-wrapper">
			<div class="pantalla">Pantalla</div>
			<div id="buy-map"></div>
		</div>
		<table class="tarjeta-form">{{ tarjeta_form.as_table }}</table>
		{% csrf_token %}
		<button type="submit">Comprar</button>
	</form>
</article>
{% endblock content %}

templates/reservas/pagar-reserva.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block head %}
{{ block.super }}
<script type="text/javascript" src="{% static "sitema-de-reserva/vendor/react/react.js" %}"></script>
<script type="text/javascript" src="{% static "sitema-de-reserva/vendor/react/react-dom.js" %}"></script>
<script type="text/javascript" src="{% static "sitema-de-reserva/js/app.js" %}"></script>
<script type="text/javascript">
$(document).ready(function() {
	let seats = {{ seats | safe}}
	let prices = {{ prices|safe }};
	let pricetypes = {{ pricetypes|safe }};
	StartSeatPricePickerList(document.querySelector('#price-selector'), {
		'prices': prices, 'priceTypes': pricetypes, 'seats': seats
	});
})
</script>
{% endblock %}

{% block content %}
<div class="topbar-placeholder"></div>
<article id="seleccion-precio">
	<form method="POST">
		{% if tarjeta_form %}
    	<h2>Datos de la tarjeta</h2>
    	<table>
			{{ tarjeta_form.as_table }}
    	</table>
		{% endif %}
    	<h2>Elegir tipo de entrada</h2>
		<div id="price-selector">
		</div>
		{% csrf_token %}
		<button type="submit" class="btn btn-primary">Enviar</button>
	</form>
</article>
{% endblock content %}

templates/reservas/ver-codigo.html
<!DOCTYPE html>
<html>
	<head>
		<style>
		html {
			font-family: sans-serif;
		}
		h1 {
			font-size: 18pt;
		}
		h2 {
			font-size: 16pt;
		}
		table {
			border-collapse: collapse;
		}
		td,th {
			border: 1px solid black;
			padding: 0.5em;
		}
		th {
			font-weight: bold;
		}
		tr th {
			text-align: right;
		}
		thead th {
			text-align: center;
		}
		tfoot {
			font-weight: bold;
		}
		svg {
			width: 100%;
		}
		p {
			margin: 0.5em;
		}
		.legend {
			font-size: 10pt;
			font-style: italic;
		}
		</style>
	</head>
	<body>
		<h2>Funcion</h2>
		<table>
			<tr><th>Fecha y hora</th><td>{{ funcion.fecha }}</td>
			<tr><th>Pelicula</th><td>{{ funcion.pelicula }}</td>
			<tr><th>Sala</th><td>{{ funcion.sala }}</td></tr>
		</table>

		<h2>Cliente</h2>
		<table>
			{% if user.persona %}
				<tr><th>Apellido</th><td>{{ user.persona.apellido }}</td></tr>
				<tr><th>Nombre</th><td>{{ user.persona.nombre }}</td></tr>
				<tr><th>Documento</th><td>{{ user.persona.tipo_dni }} &mdash; {{ user.persona.nro_dni }}</td></tr>
			{% endif %}
			<tr><th>Nombre de usuario</th><td>{{ user.username }}</td></tr>
		</table>

		<h2>Entradas</h2>
		<table>
			<thead>
				<th>Fecha y hora (compra/reserva)</th>
				<th>Butaca</th>
				<th>Estado</th>
				<th>Tipo de precio</th>
				<th>Monto</th>
			</thead>
			<tbody>
				{% for ee in estadoentradas %}
				<tr>
					<td>{{ ee.0.fecha }}</td>
					<td>{{ ee.0.entrada.butaca }}</td>
					<td>{{ ee.0.get_estado_display }}</td>
					<td>{{ ee.1.tipo_precio.nombre }}</td>
					<td>${{ ee.1.monto }}</td>
				</tr>
				{% endfor %}
			</tbody>
			<tfoot>
				<tr>
					<td></td>
					<td></td>
					<td></td>
					<td>SUBTOTAL</td>
					<td>${{ subtotal }}</td>
				</tr>
			</tfoot>
		</table>
		<svg>
		{{ code39|safe }}
		</svg>
		<p class="legend">Ticket no valido como factura</p>
		<p class="legend">El precio de las reservas no es definitivo hasta realizar el pago</p>
	</body>
</html>